name: VyOS 1.4 rolling fullconenat kernel Build and Release
permissions:
  contents: write
on:
  push:
    tags:
      - "*"
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:current
      env:
        TZ: Asia/Shanghai
      options: --privileged
      
    steps:

    - name: git clone vyos-kernel-build
      run: |
        set -eux
        
         git clone -b dev  https://github.com/debiansid/vyos-kernel-rolling linux-kernel
         
         
    - name: make kernel deb
    #  working-directory: linux-kernel
      run: |
        set -eux
        pwd

        cd linux-kernel
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.44.tar.xz
        tar xf linux-6.1.44.tar.xz
        ln -s linux-6.1.44 linux 
        ./build-kernel.sh
        rm *dev*.deb
    - name: make intel-qat deb
      run: |
        set -eux
        pwd
        cd linux-kernel
        ./build-intel-qat.sh
        cp *.deb ../
    - name: ls
      run: |
        set -eux

        pwd
        ls -lah linux-kernel

    - name: Upload release
      uses: softprops/action-gh-release@v0.1.15
      with:
          tag_name: ${{ github.ref_name }}
          files: |
               linux-kernel/linux*.deb
               linux-kernel/vyos-*.deb
          draft: true
          prerelease: true
          
