name: VyOS 1.4 fullconenat dae kernel Build and Release
permissions:
  contents: write
on:
  workflow_dispatch:
   #push:
   #tags:
   #- "*"
  
jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:current
      env:
        TZ: Asia/Shanghai
      options: --privileged
      
    steps:

    - name: git clone vyos-kernel-build
      run: |
        set -eux
        
         git clone -b dev-dae-fullconenat https://github.com/debiansid/vyos-kernel-sv-fullconenat vyos-build

    - name: make deb
    #  working-directory: vyos-kernel-sv-fullconenat
      run: |
        set -eux
        pwd
        cd vyos-build 
        wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.1.23.tar.xz
        tar xf linux-6.1.23.tar.xz
        sleep 120s
        ln -s linux-6.1.23 linux
        ./build-kernel.sh
        rm *dev".deb


    - name: ls
      run: |
        set -eux

        pwd
        ls -lah vyos-build

    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ github.ref_name }}
          files: vyos-build/linux*.deb
          draft: true
          prerelease: true
          
